### ISSUE TITLE
[SUGGESTION] Backport to 1.20.1

### ISSUE THREAD

**Issue by NextRaven10** [getkirill/invisible-deity-mod#1]
Hello, there are still a lot of mods that haven´t updated to newer versions which is the reason why I´m tied to the Minecraft version 1.20.1 but I would love to include your mod in my modpack

Thx in advance and have a nice day :)

**Comment by getkirill** [comment]
Will look into it today :)

**Comment by getkirill** [comment]
Fixed in 6956fd0 :)
You can download new version here: https://modrinth.com/mod/invisible-deity/version/1.1.1+1.20.1
